config/routes.rb
Bugflow::Application.routes.draw do
  resources :projects do
    resources :crash_groups do
      get :resolve, on: :member
    end
  end

  scope "v1" do
    post "/sync" => "v1/sync#sync"
  end

  root :to => 'projects#index'

end

app/models/crash.rb
class Crash < ActiveRecord::Base
  belongs_to :crash_group

  serialize :backtrace
  serialize :env
end

app/models/crash_group.rb
class CrashGroup < ActiveRecord::Base
  belongs_to :crash_groups
  has_many :crashes, dependent: :delete_all

  validates :message, :location, :class_name, :presence => true

  def resolved?
    self.resolved
  end

  def resolve!
    self.resolved = true
    self.crashes_count = 0
    self.save
  end


end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :project
	has_many :requests, dependent: :delete_all
	validates :location, :controller, :action, presence: true
end

app/models/project.rb
require 'digest/sha1'
class Project < ActiveRecord::Base
  validates :name, presence: true
  after_create :build_secret
  has_many :groups, dependent: :destroy

  def build_secret
    max_size = 24
    text_id = self.id.to_s(16)
    length = text_id.size

    self.secret = text_id + SecureRandom.hex(max_size-length)
    self.save
  end

  def import(requests)
    Rails.logger.debug "Decode64 data"
    data_requests = Base64.strict_decode64(requests)
    Rails.logger.debug "Decompressing data"
    data_requests = Zlib::Inflate.inflate(data_requests)
    Rails.logger.debug "Load YAML data"
    data_requests = YAML.load(data_requests)
    Rails.logger.debug "Parsing data..."
    data_requests.each do |request|
      Rails.logger.debug request.symbolize_keys.inspect
      import_one(request)
    end
  end

  def import_one(request_data)
    group = self.groups.find_or_initialize_by_location(request_data[:location])
    group.controller = request_data[:controller]
    group.action = request_data[:action]
    if group.save
      request = group.requests.new
      request.cpu = request_data[:cpu]
      request.ram = request_data[:ram]
      request.params = request_data[:params]
      request.format = request_data[:format]
      request.method = request_data[:method]
      request.path = request_data[:path]
      request.request_time = request_data[:request_time]
      request.start_time = request_data[:start_time]
      request.env = request_data[:environment]
      request.save
      Rails.logger.debug request.errors.full_messages.join(", ")
    end
  end

  def errors_count
    self.groups.count
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
	belongs_to :group
	validates :params, :format, :method, :path, :request_time, :start_time, :env, :cpu, :ram, presence: true

	serialize :params
	serialize :env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/crash_groups_controller.rb
class CrashGroupsController < ApplicationController
  http_basic_authenticate_with :name => "bury", :password => "bury"
  before_filter :preload_resource!

  def index
    #@groups = @current_project.crash_groups.order("last_error_time DESC")
  end

  def show
    @group = @current_project.crash_groups.find(params[:id])
    @crashes = @group.crashes.order("created_at DESC").limit(15)
  end

  def resolve
    @group = @current_project.crash_groups.find(params[:id])
    @group.resolve!

    redirect_to [@current_project, @group]
  end

  protected
    def preload_resource!
      @current_project = Project.find(params[:project_id])
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  http_basic_authenticate_with :name => "bury", :password => "bury"
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    if params[:project_id]
      @selected_project = Project.find(params[:project_id]) 
    else
      @selected_project = @projects.first
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    
    redirect_to [@project, :crash_groups]
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path(project_id: @project.id), notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/v1/sync_controller.rb
class V1::SyncController < ApplicationController
  def sync
   	@project = Project.find_by_secret(params[:api_key])
	@project.import(params[:data])
	render nothing: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crash_groups_helper.rb
module CrashGroupsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/v1/sync_helper.rb
module V1::SyncHelper
end

app/views/crash_groups/index.html.haml
.timeline
  .controllers
    %select
      %option Slowest average response time
      %option Apdex most dissatisfying
      %option Most time consuming
      %option Highest throughput
      %option Standard deviation
    .list
      %ul
        %li.active= link_to "DashboardController#index", "#"
        - 10.times do
          %li= link_to "DashboardController#index", "#"
  .actions
    .gutter
      .inner 
        .cursor
    .list
      .cursor
      .item.active

      - 10.times do
        .item
.summary
  .subnav
    %ul.nav.nav-pills
      %li.active= link_to "Requests", "#"
      %li= link_to "Summary", "#"
      %li= link_to "Errors", "#"
  .tab-content
    .tab-pane.active
      %table.table.table-striped.table-condensed
        %thead
          %tr
            %th{ style: "width: 14px" }
            %th{ style: "width: 36px" } Start
            %th.span1 Type
            %th.span1 Status
            %th Database Time
            %th View Time
            %th Render Count
            %th Query Count
            %th Total Time
            %th WebBrowser
            %th System
            %th Screen Resolution
        %tbody
          - 30.times do
            %tr
              %td 
                %i.icon-chevron-right
              %td 13:00
              %td GET
              %td 200
              %td 10000 ms
              %td E
              %td E
              %td E
              %td E
              %td E
              %td E
              %td E
.info-pane
  .page-header
    %a.close &times;
    %h4 Request Summary
  %table.table.table-striped.table-bordered.table-condensed
    %tr
      %th.span2 Status
      %td 200
    %tr
      %th.span2 Method
      %td GET
    %tr
      %th.span2 Database Time
      %td 200
    %tr
      %th.span2 View Time
      %td 200
    %tr
      %th.span2 Render Count
      %td 200
    %tr
      %th.span2 Query Count
      %td 200
    %tr
      %th.span2 Total Time
      %td 200
    %tr
      %th.span2 WebBrowser
      %td 200
    %tr
      %th.span2 System
      %td 200
    %tr
      %th.span2 Screen Resolution
      %td 200
    %tr
      %th.span2 IP
      %td 200
  .page-header
    %h4 Queries
  %table.table.table-striped.table-bordered.table-condensed
    %thead
      %tr
        %th Name
        %th Time
        %th SQL
    %tbody
      %tr
        %td Project Load
        %td 0.4ms
        %td SELECT `projects`.* FROM `projects` WHERE `projects`.`id` = 1 LIMIT 1
      %tr
        %td Project Load
        %td 0.4ms
        %td SELECT `projects`.* FROM `projects` WHERE `projects`.`id` = 1 LIMIT 1
      %tr
        %td Project Load
        %td 0.4ms
        %td SELECT `projects`.* FROM `projects` WHERE `projects`.`id` = 1 LIMIT 1
      %tr
        %td Project Load
        %td 0.4ms
        %td SELECT `projects`.* FROM `projects` WHERE `projects`.`id` = 1 LIMIT 1
  .page-header
    %h4 Render
  %table.table.table-striped.table-bordered.table-condensed
    %thead
      %tr
        %th Time
        %th File
    %tbody
      %tr
        %td 0.4ms
        %td shared/_flash_messages.html.haml
      %tr
        %td 0.4ms
        %td shared/_flash_messages.html.haml
      %tr
        %td 0.4ms
        %td shared/_flash_messages.html.haml
      %tr
        %td 0.4ms
        %td shared/_flash_messages.html.haml
  .page-header
    %h4 External Requests
  %table.table.table-striped.table-bordered.table-condensed
    %thead
      %tr
        %th Time
        %th URL
    %tbody
      %tr
        %td 0.4ms
        %td api.twitter.com
      %tr
        %td 0.4ms
        %td api.twitter.com
      %tr
        %td 0.4ms
        %td api.twitter.com

app/views/dashboard/index.html.haml
.page-header
  %h2 
    Templaty
    %small your project

%ul.nav.nav-pills
  %li.active= link_to "All", "#"
  %li= link_to "Fixed", "#"
  %li= link_to "Pending", "#"
  %li.pull-right{ style: "float: right" }= link_to "Install Gem", "#"

%table.table.table-striped.table-bordered
  %thead
    %th.span1 UID
    %th Message
    %th.span3 Location
    %th.span2 Latest
    %th.span1 Count
  %tbody
    - 60.times do
      %tr
        %td
          \#22
        %td
          %a{ href: "#" } (NameError) "undefined local variable or method `keywords_url' for #<KeywordsController:0x2b88debb7960>"
        %td
          Dashboard#index
        %td
          10 seconds ago
        %td
          .label.label-info 10

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BugFlow
    = csrf_meta_tags
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"

  %body{ :id => "controller_#{controller.controller_name}_#{controller.action_name}" }
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          = link_to root_url, class: "brand" do
            BugFlow
          %ul.nav.pull-left
            %li.dropdown
              = link_to "#", class: "dropdown-toggle", data: { toggle: "dropdown" } do
                %i.icon-fire.icon-white
                My Apps
                %b.caret
              %ul.dropdown-menu
                - Project.all.each do |project|
                  %li= link_to project.name, project
                %li.divider
                %li= link_to "Show All", projects_path
            %li
              = link_to "#" do
                %i.icon-cog.icon-white
                Settings

            %li.divider-vertical
            %li
              = link_to new_project_path, id: "submit_app" do
                %i.icon-plus.icon-white
                Add project
          %ul.nav.pull-right
            %li
              = link_to "#" do
                %i.icon-off.icon-white
                Logout
      .clear 
    
    .clear
    .container-fluid
      = render partial: "shared/flash_messages"
      .clear
      = yield
      .clear
    = yield :footer

app/views/projects/_form.html.haml
= simple_form_for @project, :html => {:class => 'form-horizontal' } do |f|
  = f.input :name
  .actions
    = f.submit 'Save', class: "btn btn-primary"

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
.row
  .span12
    %ul.breadcrumb
      %li= "Projects"
.row
  .span12
    .page-header
      %h2 Your Projects
.row
  .span3
    %ul.nav.nav-pills.nav-stacked
      - @projects.each do |project|
        %li{ class: @selected_project && @selected_project.id == project.id ? "active" : nil }
          = link_to '#project_'+project.id.to_s, { data: { toggle: "pill" } } do
            %span.pull-right
              %b= project.errors_count
            = project.name
            
  .span9
    .tab-content
      - @projects.each do |project|
        .tab-pane{ id: "project_#{project.id}", class: @selected_project && @selected_project.id == project.id ? "active" : nil }
          .row
            .span9
              .page-header
                %h3
                  = link_to "Show Errors", project, class: "btn btn-success btn-large pull-right"
                  = project.name
              %h4 Current API key:
              %br/
              %pre= project.secret
          .row
            .span4
              %h4 Setting up your Rails 3.x app
              %p Add the BugFlow gem to your Gemfile. In Gemfile:
              %pre gem "bugflow"
              %p Then from your project's Rails.root, run:
              %pre bundle install
              %p The Rails gem will catch error in Rails Controllers, Rails Metal and Rack Middleware by default. View the README for a bunch more details about additional functionality provided by the notifier.
            .span5 
              %h4 Setting up your rack Application
              %p In order to use bugflow in a non-Rails rack app, just load the bugflow gem, configure your API key, and use the BugFlow::Rack middleware
              %p View the README for a bunch more details about additional functionality provided by the notifier.

app/views/projects/new.html.haml
.page-header
  %h2 New project

= render 'form'

app/views/shared/_flash_messages.html.haml
- flash.each do |type, msg|
  .alert{ class: ["alert",type].join("-") }
    %a.close{ href: "#" } ×
    = msg